### PR TITLE
Fix app distribution api.txt files.

### PR DESCRIPTION
**Pull request by ehsannas**

### CODE REVIEW

**Comment by ehsannas** [comment]
tip-of-tree seems to be broken. (Running `./gradlew :firebase-app-distribution:apiInformation` fails).

This change automatically generated by running `./gradlew :firebase-app-distribution:generateApiTxtFile`

**Review by rachaprince — APPROVED** [review]
Sorry for the delay on this review. Thank you for putting this together.

It looks like there are still a few lint tests that are failing

**Comment by rachaprince** [comment]
I created https://github.com/firebase/firebase-android-sdk/pull/3232 which also includes a re-generation of the kotlin api files to get the api-information check to pass

**Comment by ehsannas** [comment]
Thanks @rachaprince . I'll close this PR in favor of #3232

**Pull request closed without merging**
