### PR TITLE
Update versions in gradle.properties

### PR DESCRIPTION
**Pull request by rlazo**

### CODE REVIEW

**Review by vkryachko — APPROVED** [review]
Adding @yifanyang due to smoke tests failure

**Comment by yifanyang** [comment]
/test smoke-tests

> Adding @yifanyang due to smoke tests failure

Not sure why but there was no log for the smoke tests failure. Let's rerun it and see.

**Review by yifanyang — APPROVED** [review]
/test smoke-tests

> > Adding @yifanyang due to smoke tests failure
> 
> Not sure why but there was no log for the smoke tests failure. Let's rerun it and see. I think the failure should have nothing to do with this pull request.

The second run ([link](https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/3843/smoke-tests/1540377559248670720/)) failed with a flake from firestore tests, which should be irrelevant.

**Pull request merged**
