### PR TITLE
Port "Stop persisting last acknowledged batch ID" from iOS

### PR DESCRIPTION
**Pull request by var-const**
A straightforward port of https://github.com/firebase/firebase-ios-sdk/pull/2243.

### CODE REVIEW

**Comment by var-const** [comment]
> add a comment to SQLiteSchema.java that last_acknowledged_batch_id is no longer used?

Added above the migration to remove acknowledged mutations, let me know if I should move it to a more prominent place.

**Comment by wilhuff** [comment]
Database smoke tests are known flaky and we haven't yet constrained the smoke-tests-* tasks to run only affected changes so proceeding.

**Pull request merged**
