### PR TITLE
rebase fad/in-app-feedback onto fad/next

### PR DESCRIPTION
**Pull request by kaibolay**

### CODE REVIEW

**Comment by kaibolay** [comment]
I don't understand the diffs. They somehow contain all changes we already have on fad/in-app-feedback

**Comment by kaibolay** [comment]
merge instead of rebase: #4107 - let's pick one

**Comment by jladieu** [comment]
This seems...not great, I'd say let's go with the merge alternative.

**Comment by kaibolay** [comment]
going with https://github.com/firebase/firebase-android-sdk/pull/4107

**Pull request closed without merging**
