### PR TITLE
Ml logging

### PR DESCRIPTION
**Pull request by annzimmer**

### CODE REVIEW

**Comment by rlazo** [comment]
Looks like you're also removing transport from the deps. Is it no longer needed?

**Comment by annzimmer** [comment]
I moved the transport dep to the FirebaseMlLogger - that way I won't have to pass it into every class - just have each class that needed logging get an instance of the FirebaseMlLogger. Hoping that was appropriate.

**Comment by rlazo** [comment]
> I moved the transport dep to the FirebaseMlLogger - that way I won't have to pass it into every class - just have each class that needed logging get an instance of the FirebaseMlLogger. Hoping that was appropriate.

Yes, definitely. Just checking 👍

**Review by rlazo — APPROVED** [review]

**Pull request merged**
