### PR TITLE
Remove KTX docs from firebaseopensource.com

### PR DESCRIPTION
**Pull request by samtstern**
This will remove the sidebar from this page:
https://firebaseopensource.com/projects/firebase/firebase-android-sdk/

Someone else can decide if we actually want to delete all the individual md files listed here:
https://github.com/firebase/firebase-android-sdk/tree/master/docs#kotlin-extensions

### CODE REVIEW

**Review by rlazo — APPROVED** [review]

**Comment by samtstern** [comment]
@rlazo can you merge this with your admin rights?  I can't imagine that test failure is real.

**Review by rachelsaunders — APPROVED** [review]

**Comment by samtstern** [comment]
@rlazo is there anything I can do to help with this or are you just using this as a reason to look into flaky tests?

**Comment by rlazo** [comment]
Hi @samtstern there's nothing pending on your side. I'm looking into the flaky test. Sorry for the delay.

**Comment by samtstern** [comment]
@rlazo sgtm and no rush on this!  I just feel bad you've had to prod it so many times.

**Comment by rlazo** [comment]
> @rlazo sgtm and no rush on this! I just feel bad you've had to prod it so many times.

np! Yeah, not the best that it's taking so long, but that's on us since we have to keep it healthy 😄

**Pull request merged**
