### PR TITLE
remove dismiss listener

### PR DESCRIPTION
**Pull request by s2g090123**
There is no way to remove dismiss listeners.
So I add this part at `removeDismissListener` and `removeAllListeners`.

### CODE REVIEW

**Comment by thatfiredev** [comment]
@s2g090123 Can you expand your use case into detail? Why would you like to have the ability to remove dismiss listeners?

**Comment by s2g090123** [comment]
Hi @thatfiredev. Thanks for your reply.
I am using FirebaseInAppMessaging and add a dismiss listener in a activity.
But I get a memory leak from LeakCanary when the activity is destroyed after rotating screen.

Below is my code (it's very simple)
```kotlin
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        FirebaseInAppMessaging.getInstance().addDismissListener {
            onDismiss()
        }
    }

    private fun onDismiss() {
        // handle onDismiss
    }
}
```

Leak trace in LeakCanary

> ┬───
│ GC Root: System class
│
├─ android.provider.FontsContract class
│    Leaking: NO (MyApplication↓ is not leaking and a class is never leaking)
│    ↓ static FontsContract.sContext
├─ com.example.inappmessagetest.MyApplication instance
│    Leaking: NO (Application is a singleton)
│    mBase instance of android.app.ContextImpl
│    ↓ Application.mActivityLifecycleCallbacks
│                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~
├─ java.util.ArrayList instance
│    Leaking: UNKNOWN
│    Retaining 1.4 kB in 44 objects
│    ↓ ArrayList.elementData
│                ~~~~~~~~~~~
├─ java.lang.Object[] array
│    Leaking: UNKNOWN
│    Retaining 1.3 kB in 43 objects
│    ↓ Object[].[3]
│               ~~~
├─ com.google.firebase.inappmessaging.display.FirebaseInAppMessagingDisplay
│  instance
│    Leaking: UNKNOWN
│    Retaining 953 B in 37 objects
│    application instance of com.example.inappmessagetest.MyApplication
│    ↓ FirebaseInAppMessagingDisplay.headlessInAppMessaging
│                                    ~~~~~~~~~~~~~~~~~~~~~~
├─ com.google.firebase.inappmessaging.FirebaseInAppMessaging instance
│    Leaking: UNKNOWN
│    Retaining 100.0 kB in 1502 objects
│    ↓ FirebaseInAppMessaging.developerListenerManager
│                             ~~~~~~~~~~~~~~~~~~~~~~~~
├─ com.google.firebase.inappmessaging.internal.DeveloperListenerManager instance
│    Leaking: UNKNOWN
│    Retaining 98.2 kB in 1461 objects
│    ↓ DeveloperListenerManager.registeredDismissListeners
│                               ~~~~~~~~~~~~~~~~~~~~~~~~~~
├─ java.util.HashMap instance
│    Leaking: UNKNOWN
│    Retaining 98.0 kB in 1457 objects
│    ↓ HashMap.table
│              ~~~~~
├─ java.util.HashMap$Node[] array
│    Leaking: UNKNOWN
│    Retaining 98.0 kB in 1456 objects
│    ↓ HashMap$Node[].[0]
│                     ~~~
├─ java.util.HashMap$Node instance
│    Leaking: UNKNOWN
│    Retaining 97.9 kB in 1452 objects
│    ↓ HashMap$Node.key
│                   ~~~
├─ com.example.inappmessagetest.MainActivity$$ExternalSyntheticLambda0 instance
│    Leaking: UNKNOWN
│    Retaining 97.8 kB in 1450 objects
│    f$0 instance of com.example.inappmessagetest.MainActivity with mDestroyed
│    = true
│    ↓ MainActivity$$ExternalSyntheticLambda0.f$0
│                                             ~~~
╰→ com.example.inappmessagetest.MainActivity instance
     Leaking: YES (ObjectWatcher was watching this because com.example.
     inappmessagetest.MainActivity received Activity#onDestroy() callback and
     Activity#mDestroyed is true)
     Retaining 97.8 kB in 1449 objects

If you require any further information, feel free to contact me. Thanks!

**Comment by thatfiredev** [comment]
@s2g090123 Thank you for explaining.
I'll wait for one of the engineers on the In-App Messaging team to review this.

**Review by eldhosembabu — COMMENTED** [review]
Working on API review for the same.

**Comment by Aslamxtc** [comment]
Is minebase a failed token

**Comment by Aslamxtc** [comment]
Is minebase a failed token

**Comment by eldhosembabu** [comment]
API review Approved: b/262402247

**Comment by eldhosembabu** [comment]
@s2g090123 could you please correct the Unit tests and other checks?

**Comment by eldhosembabu** [comment]
Since there is some more additional changes needed, I've created a new PR copying your change with the additional changes here: https://github.com/firebase/firebase-android-sdk/pull/4492

So closing this PR.

**Pull request closed without merging**
