### PR TITLE
Upgrade Firestore's GRPC to 1.26

### PR DESCRIPTION
**Pull request by schmidt-sebastian**

### CODE REVIEW

**Comment by f0rev** [comment]
@schmidt-sebastian when do you plan merge this?

**Comment by schmidt-sebastian** [comment]
> @schmidt-sebastian when do you plan merge this?

Unfortunately, this turns out to be a breaking change for our SDKs as it creates incompatibilities between the different Firebase products. It will likely be a while before we can release this change

**Comment by easytoo12** [comment]
You say "a while" do you have an estimate?

**Comment by schmidt-sebastian** [comment]
> You say "a while" do you have an estimate?

I chose my words carefully because I don't. Our next breaking change release is slated for May, but we can potentially move this up if there is enough demand.

**Comment by easytoo12** [comment]
Sooner would be a great help

**Comment by CWftw** [comment]
We have not been able to update to the latest versions of Firebase due to incompatibilities between protobuf java, java-lite and lite. Our best way forward seems to be waiting for Firebase to move to java-lite, and migrate our legacy code to java-lite. Therefore I agree that the sooner the better as I would like to stay up to date with Firebase releases.

**Comment by thaidn** [comment]
+1 if you can make this happen sooner. A couple of Tink users are being blocked by this.

**Comment by easytoo12** [comment]
Do you have an update on this Schmidt-Sebastian?

**Comment by schmidt-sebastian** [comment]
> Do you have an update on this Schmidt-Sebastian?

We don't have much in terms of good news here. At this point it looks like we may bundle this change with other breaking changes in or around May.

**Comment by easytoo12** [comment]
Hey Schmidt-sebastian is this still in the works for May?

**Comment by schmidt-sebastian** [comment]
> Hey Schmidt-sebastian is this still in the works for May?

Yep!

**Comment by schmidt-sebastian** [comment]
@ashwinraghav Can you re-assign this to someone that can resolve the remaining symbol conflicts?

**Comment by ZacSweers** [comment]
Hey folks, this change is fixing a significant compatibility issue between firebase and any app using protobufs. It seems to have stalled activity-wise, are there plans to resume?

**Comment by thaidn** [comment]
FWIW we've decided to shade our copy of protobuf-javalite in Tink, starting from Tink 1.4.0-RC2 (which is coming next week).

I recommend Firebase doing the same. https://github.com/google/tink/commit/ae241770f030fb82977a64c982f870de87231635 is our implementation, should be straight-forward to copy to Firebase.

**Comment by schmidt-sebastian** [comment]
We are still working on this, but have moved active development to a new PR: https://github.com/firebase/firebase-android-sdk/pull/1534/files

**Pull request closed without merging**
