### PR TITLE
Reset Client Health Metrics, if it is too old.

### PR DESCRIPTION
**Pull request by James201311**
Reset CLient Health Metrics, if it's one week old.

### CODE REVIEW

**Review by vkryachko — COMMENTED** [review]
I don't recall this discussion, is it actually desired to delete events older than 1 week?

**Comment by James201311** [comment]
The plan was to remove old metrics to avoid it taking up too much storage space, since the storage size will be linear to the number of log sources, and its size is negligible. We will not have this implementation.

**Pull request closed without merging**
