### PR TITLE
If modelHash is null pass emptyString to logger which requires non-nu…

### PR DESCRIPTION
**Pull request by kabeer-uber**
…ll modelHash

Fixes https://github.com/firebase/firebase-android-sdk/issues/3940

### CODE REVIEW

**Review by vkryachko — APPROVED** [review]

**Comment by kabeer-uber** [comment]
Thanks @vkryachko for the approval, looking forward to the merge and release in the next version.

**Comment by vkryachko** [comment]
also fyi @rlazo

**Review by rlazo — APPROVED** [review]

**Pull request merged**
