### PR TITLE
Fix StackOverflowError by deeply nested server-timestamps.

### PR DESCRIPTION
**Pull request by sk-takahiro-kurebayashi**
# Summary
This PR fixes app crash by `StackOverflowError` while saving the document overlay cache into SQLite database inside of Firestore library.

See: https://github.com/firebase/firebase-android-sdk/issues/4702

# Notes
This PR cannot fix `StackOverflowError` raised while loading the document overlay cache from SQLite database.
To avoid this crash, we can clear persistent storage by [`FirebaseFirestore#clearPersistence`](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/firestore/FirebaseFirestore#clearPersistence()) when  right after the app launch.

### CODE REVIEW

**Comment by sk-takahiro-kurebayashi** [comment]
Hi @ehsannas, let me know how to resolve `pr-message` check failure. Which feature-branch should I change base-branch to?

**Review by ehsannas — APPROVED** [review]

**Comment by ehsannas** [comment]
@sk-takahiro-kurebayashi Thanks for your contribution! 🎉

**Comment by ehsannas** [comment]
Looks like I need to roll back this change as there were a few integration test failures that were skipped by the CI in this PR.

**Comment by ehsannas** [comment]
I'll look into the failures and fix them as needed.

**Comment by ehsannas** [comment]
For now, rolling this PR back via https://github.com/firebase/firebase-android-sdk/pull/4761

**Pull request merged**
