### PR TITLE
Fix  ClassNotFoundException for com.google.firebase.remoteconfig.ktx.…

### PR DESCRIPTION
**Pull request by b95505017**
…FirebaseConfigKtxRegistrar

Should be `FirebaseRemoteConfigKtxRegistrar`

### CODE REVIEW

**Comment by rlazo** [comment]
Hi @b95505017 Great catch! Please, also add to your PR the missing test that should have caught this earlier.

```
 @RunWith(RobolectricTestRunner::class)
  class LibraryVersionTest : BaseTestCase() {
      @Test
      fun `library version should be registered with runtime`() {
          val publisher = Firebase.app.get(UserAgentPublisher::class.java)
          assertThat(publisher.userAgent).contains(LIBRARY_NAME)
      }
  }
```

Thank you for contributing to Firebase!

**Comment by wbervoets** [comment]
any update when this will be fixed in a released version?

**Comment by rlazo** [comment]
Thanks for the heads up @wbervoets I'll approve and merge this CL as-is, and add the missing test in a follow-up PR. Thanks for your contribution to Firebase @b95505017 !

**Pull request merged**
