### PR TITLE
Public Count

### PR DESCRIPTION
**Pull request by wu-hui**

### CODE REVIEW

**Review by dconeybe — APPROVED** [review]
LGTM

**Comment by dconeybe** [comment]
Do you need to update `firebase-firestore/api.txt`, like #3664 did for TransactionOptions?

**Comment by wu-hui** [comment]
> Do you need to update `firebase-firestore/api.txt`, like #3664 did for TransactionOptions?

Yep, thanks for the catch.

**Comment by dconeybe** [comment]
Add a change log entry to `firebase-firestore/CHANGELOG.md`

e.g.
```
- [feature] Added `Query.count()`, which fetches the number of documents in the
  result set without actually downloading the documents (#4130).
```

**Review by dconeybe — CHANGES_REQUESTED** [review]
Add change log entry

**Review by dconeybe — APPROVED** [review]

**Pull request merged**
