### PR TITLE
Enabled linting on Firestore

### PR DESCRIPTION
**Pull request by ashwinraghav**
This change whitelists errors thrown by linter that we know about and documents why these are reasonable.
We enable linter.

### CODE REVIEW

**Comment by wilhuff** [comment]
The asserts come from sources in google3 and are shared with the server
where asserts do work. Please don’t change this.

**Comment by wilhuff** [comment]
Neither of these changes are really OK:
  * The source for the number encoding is shared with the server, internal, and not third_party so every sync will overwrite these changes
  * The listenTargets map you're replacing is known to get to thousands of entries.

**Comment by ashwinraghav** [comment]
> * The source for the number encoding is shared with the server, internal, and not third_party so every sync will overwrite these changes

Is it acceptable to us that the assert statements do not actually work in the Android Runtime ?

**Comment by wilhuff** [comment]
> > * The source for the number encoding is shared with the server, internal, and not third_party so every sync will overwrite these changes
> 
> Is it acceptable to us that the assert statements do not actually work in the Android Runtime ?

In principle no, but there's a trade-off to be made. Every write on the backend is going through this code so the likelihood of an android client tripping over this is miniscule. On the other side is having to avoid clobbering this with every update we get from the server.

The only way to "fix" these assertions is to rewrite these in the copybara script.

**Comment by ashwinraghav** [comment]
Ok. Given that we have consciously thought through these errors, I have explicitly whitelisted these cases and in general enabled the linter.
Let me know if this looks reasonable.

**Pull request merged**
