### PR TITLE
Re-establish streams when App Check token expires.

### PR DESCRIPTION
**Pull request by ehsannas**

### CODE REVIEW

**Review by schmidt-sebastian — COMMENTED** [review]
Please add change log to firebase-firestore/CHANGELOG.md

**Review by schmidt-sebastian — APPROVED** [review]

**Comment by schmidt-sebastian** [comment]
@ehsannas Can you add a Changelog entry?

**Comment by ehsannas** [comment]
oops. Done via https://github.com/firebase/firebase-android-sdk/pull/3349

**Pull request merged**
