### PR TITLE
Removing getRunningAppProcesses since the process_name isn't used

### PR DESCRIPTION
**Pull request by raymondlam**
getRunningAppProcesses() was also causing compliance issues with Tencent's appstore #4045

### CODE REVIEW

**Review by jeremyjiang-dev — APPROVED** [review]
Thanks for fixing this!

**Comment by jeremyjiang-dev** [comment]
The failing unit test seems to be flaky

**Review by visumickey — APPROVED** [review]
Thanks for making these changes!

**Pull request merged**
