### PR TITLE
Lazy initialize dataFile in PersistedInstallation

### PR DESCRIPTION
**Pull request by carlonzo**
tries to solve https://github.com/firebase/firebase-android-sdk/issues/3313

the `dataFile` is initialized lazily from methods that are supposed to be already be called from a dedicated IO thread given they perform disk ops

### CODE REVIEW

**Comment by carlonzo** [comment]
thanks! please

/retest

**Comment by carlonzo** [comment]
hi @yoyomyo,
the test `device-check-changed` fails due to the failure of `:firebase-crashlytics:firebase-test-labUpload` but I cant find the reason this is related to my PR. also logs https://storage.googleapis.com/android-ci/pr-logs/pull/firebase_firebase-android-sdk/3314/device-check-changed/1484436446457630724/build-log.txt do not give me any hint on whats happening. you mind giving me an hint?

**Comment by yoyomyo** [comment]
@carlonzo Thank you for following up! The test failure does not seem related to this PR. I have reached out to the wider SDK team for support since I am not super familiar with the `firebase-crashlytics:firebase-test-labUpload` error. And I hope you don't mind me rerunning the test just to see what happens.
/retest

**Comment by carlonzo** [comment]
@yoyomyo ofc thanks. Please let me know if there is anything I can do to help

**Comment by yoyomyo** [comment]
@carlonzo we submitted a fix for the test breakage. Please try to sync and run the failed test again.  Thank you!

**Review by yoyomyo — APPROVED** [review]

**Comment by rlazo** [comment]
Thanks for your contribution @carlonzo !

**Comment by carlonzo** [comment]
no prob @rlazo @yoyomyo thanks for your quick feedbacks. now that I know you guys are nice, I'll send more :smile:

**Pull request merged**
