### PR TITLE
Fix reflection error in com.google.android.datatransport.Priority when using aggressive Proguard rules.

### PR DESCRIPTION
**Pull request by mrichards**
The enum's values are accessed via reflection, so aggressive Proguard
rules can cause it to be stripped out.
e.g., https://github.com/firebase/firebase-android-sdk/issues/1996

### CODE REVIEW

**Comment by mrichards** [comment]
@vkryachko Are you aware of other places where reflection is used in datatransport? This rule will fix a Crashlytics customer crash. Could there be similar issues lurking for other SDKs?

**Comment by vkryachko** [comment]
@mrichards I think the underlying issue is the fact that datatransport uses an `EnumMap` internally, which for reasons beyond my understanding uses reflection, I got burnt by an `EnumSet` previously and changed it to a plain `HashSet`. I wonder if a cleaner fix in this case would be to change `EnumMap` to `HashMap` in https://github.com/firebase/firebase-android-sdk/blob/12ae453dc92424ce3163089c0d3ec33060b4fbcc/transport/transport-runtime/src/main/java/com/google/android/datatransport/runtime/util/PriorityMapping.java#L24

**Comment by mrichards** [comment]
> @mrichards ... I wonder if a cleaner fix in this case would be to change `EnumMap` to `HashMap` in...

Yes, that worked. See most recent commit.

**Review by vkryachko — APPROVED** [review]
LGTM, thanks for the fix!

**Pull request merged**
