### PR TITLE
Fiam upgrade Picasso to 2.71828 and okhttp to 3.12.0

### PR DESCRIPTION
**Pull request by kitek**

### CODE REVIEW

**Comment by vkryachko** [comment]
Hi @kitek ,

Thanks for the contribution. Before looking at the code changes I'd like to understand what motivated you to the upgrade to okhttp3?

The challenge with upgrading it is that firebase SDKs(including fiam) use grpc with the okhttp backend which depends on okhttp2. While this upgrade won't break that, this will introduce an additional dependency and as a result fiam will depend on both versions of okhttp. While I am not opposed to it in principle, I'd like to understand whether it actually solves a problem for you.

cc @MeghaB

**Comment by kitek** [comment]
Hi @vkryachko, the main reason is... Picasso. Version 2.7xxx is no more compatible with the previous 2.5.x :( Unfortunately, new version require okhttp 3.10.x 

It would be great to make fiam picasso independent or provide a way to load images with your custom implementation... or could you give me any hints how to use fiam with Picasso 2.7xxx?

**Comment by vkryachko** [comment]
Hey @kitek,

Sorry for the delay. Looking at picasso's [changelog](https://github.com/square/picasso/blob/master/CHANGELOG.md#version-271828-2018-03-07) it seems to be a sort of experimental release that is pre-3.0. So it seems like we should wait at least till 3.0 proper is released before making a decision to upgrade. And even then we will face issues where users want to keep using 2.x vs 3.x, so I'd say we need to collect more feedback from users as to which version we support.

**Pull request closed without merging**
