### PR TITLE
Update `performance-gradle` to `perf-plugin`

### PR DESCRIPTION
**Pull request by jeremyjiang-dev**
I recently updated the folder structure of fireperf plugin in the gradle repo and this needs to be updated.

### CODE REVIEW

**Review by visumickey — APPROVED** [review]
Thanks for making this change Jeremy. Is this the reason for the recent failure/bugs we received this schedule?

**Comment by jeremyjiang-dev** [comment]
> Thanks for making this change Jeremy. Is this the reason for the recent failure/bugs we received this schedule?

No really. This is for the gradle plugin marker artifact generation where I renamed the directory for the plugin.

**Review by leotianlizhan — APPROVED** [review]

**Pull request merged**
