### PR TITLE
Revert "Make FetchType header capitalized to match backend"

### PR DESCRIPTION
**Pull request by qdpham13**
Reverts firebase/firebase-android-sdk#4620

### CODE REVIEW

**Comment by danasilver** [comment]
What's the "correct" state for the header? We can migrate/fix it in the SDKs while making the backend adaptable to both

**Comment by qdpham13** [comment]
> What's the "correct" state for the header? We can migrate/fix it in the SDKs while making the backend adaptable to both

The backend has the header values as all caps but the change that I'm going to make in the backend will make the header case-insensitive. So it's up to us if we want to update the header value in the SDKs to be all caps as well or just leave it as is, it won't affect the behavior once the backend change is submitted

**Comment by danasilver** [comment]
Got it. It makes sense to me the backend and frontend align for simplicity, even if the backend is resilient to any casing. IIUC that means the client sends it uppercased

**Comment by qdpham13** [comment]
> Got it. It makes sense to me the backend and frontend align for simplicity, even if the backend is resilient to any casing. IIUC that means the client sends it uppercased

Yeah that makes sense. Going to go ahead and close this PR that reverts the capitalization change

**Pull request closed without merging**
