### PR TITLE
feat(database-ktx): add reified function getValue() to MutableData

### PR DESCRIPTION
**Pull request by rosariopfernandes**
This allows developers to use `mutableData.getValue<Post>()` instead of `mutableData.getValue(Post::class.java)` in Transactions.

### CODE REVIEW

**Comment by vkryachko** [comment]
@rosariopfernandes thanks for the contribution! I've kicked off our internal API review and will update the PR with the outcome.

**Comment by vkryachko** [comment]
@rosariopfernandes Good news! The new apis are approved, I will LGTM once the tests pass. thanks

**Comment by rosariopfernandes** [comment]
@vkryachko Thanks for the update! :)

The tests are currently failing with:
```
 * What went wrong:
Execution failed for task ':firebase-database:verifyGoogleJavaFormat'.
> Problems: formatting style violations 
```

But that task completes successfully on my machine. Any idea what might be going on?

**Comment by rosariopfernandes** [comment]
@vkryachko Thanks for the confirmation.

(Also, if you're hoping I'll merge it myself, let me tell you I don't have permissions to do so.) :rofl:

**Comment by vkryachko** [comment]
@rosariopfernandes oops, good point :) merging now

**Pull request merged**
