### PR TITLE
fix synchrnoized wrong object while manipulating appColdStartSubscribers

### PR DESCRIPTION
**Pull request by Knight-ZXW**

### CODE REVIEW

**Review by 88rogikl88 — CHANGES_REQUESTED** [review]
@rogikl88

**Review by jeremyjiang-dev — APPROVED** [review]
Thanks for catching and fixing this!

**Comment by Knight-ZXW** [comment]
@jeremyjiang-dev  could you merge this MR?

**Comment by jeremyjiang-dev** [comment]
@yifanyang Could you take a look why the api check is still in progress?

**Comment by yifanyang** [comment]
@jeremyjiang-dev 

> @yifanyang Could you take a look why the api check is still in progress?

We recently migrated presubmit jobs to GitHub Actions. I suppose this pull request was created during the short period where the the api job was removed from Prow, but GitHub is still expecting it. Anyway, I have merged it manually.

**Comment by jeremyjiang-dev** [comment]
> @jeremyjiang-dev
> 
> > @yifanyang Could you take a look why the api check is still in progress?
> 
> We recently migrated presubmit jobs to GitHub Actions. I suppose this pull request was created during the short period where the the api job was removed from Prow, but GitHub is still expecting it. Anyway, I have merged it manually.

Thank you, Yifan!

**Pull request merged**
