### PR TITLE
Temporarily disbale a smoke test case for Crashlytics.

### PR DESCRIPTION
**Pull request by yifanyang**

### CODE REVIEW

**Comment by yifanyang** [comment]
Commenting out a Crashlytics test case temporarily to make smoke test suite green.

The test case in question relies on the visibility change of fields `core` and `breadcrumbSource`, which will be available in `18.2.0` (to be released in `M100`). It is expected to fail when smoke test builds it with `18.1.0` (the gmaven latest at the moment). 

The visibility change was introduced in #2737. However, the smoke test for that PR didn't expose this failure. For some reason, the test BoMs supposed to build with gmaven version `18.1.0` ([release-smoke-test](https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/2737/smoke-tests/1413566148632383494/#0:build-log.txt%3A57), [release-headPiper-smoke-test](https://android-ci.firebaseopensource.com/view/gcs/android-ci/pr-logs/pull/firebase_firebase-android-sdk/2737/smoke-tests/1413566148632383494/#0:build-log.txt%3A59)) both pined `firebase-crashlytics` to `18.0.2-SNAPSHOT`. This may indicate some issue in logic that produces all the test BoMs in firehorn runner.

**Review by vkryachko — APPROVED** [review]

**Pull request merged**
