### PR TITLE
Fix markdown remnants

### PR DESCRIPTION
**Pull request by alexg33**
That show up in the generated docs: https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/SnapshotMetadata#isFromCache()

### CODE REVIEW

**Comment by wilhuff** [comment]
I think the build is going to complain that this isn't formatted correctly. Please run

```
./gradlew :firebase-firestore:googleJavaFormat
```

**Comment by alexg33** [comment]
> I think the build is going to complain that this isn't formatted correctly. Please run
> 
> ```
> ./gradlew :firebase-firestore:googleJavaFormat
> ```

Per usual, you're right — fixed to use the proper {@code} notation.

**Comment by alexg33** [comment]
I can't merge this guy, but I'm under the impression that check-changed weirdness is not a legit thing...

**Comment by wilhuff** [comment]
Yeah the issue is you're not allowed to commit unless the source has been run through the auto-formatter. Among other things, it reflows the paragraph text in comments.

**Pull request closed without merging**
