### PR TITLE
Clean up unused files and update README in Fireperf.

### PR DESCRIPTION
**Pull request by jeremyjiang-dev**

### CODE REVIEW

**Comment by ramanpreetSinghKhinda** [comment]
I think we need proguard file. Isn't it?

https://github.com/FirebasePrivate/firebase-android-release/blob/master/firebase-perf/proguard-rules.pro

**Review by ramanpreetSinghKhinda — APPROVED** [review]

**Comment by visumickey** [comment]
@jeremyjiang-dev Where did these files from at the first place? Atleast the crash dump.

**Review by visumickey — APPROVED** [review]

**Comment by jeremyjiang-dev** [comment]
> @jeremyjiang-dev Where did these files from at the first place? Atleast the crash dump.

Discussed offline. This file is generated accidentally on my machine and it is fine to remove it.

**Comment by jeremyjiang-dev** [comment]
> I think we need proguard file. Isn't it?
> 
> https://github.com/FirebasePrivate/firebase-android-release/blob/master/firebase-perf/proguard-rules.pro

The content in this file is all commented out. It is fine to remove it.

**Pull request merged**
