### PR TITLE
Fix header links to API subsections

### PR DESCRIPTION
**Pull request by edenman**

### CODE REVIEW

**Comment by samtstern** [comment]
(@edenman we don't actually think your `README` change broke the tests, we're just using your PR as a guinea pig for our process.  Will merge soon!)

**Comment by edenman** [comment]
Thanks team!

Next plz open source the bot, it looks awesome.

**Comment by vkryachko** [comment]
@edenman the functionality of @firebase-oss-bot is driven by Prow which is an open-source CI system: https://github.com/kubernetes/test-infra/tree/master/prow

**Pull request merged**
