### PR TITLE
- Changes to protoc version to make it working for m1 macs.

### PR DESCRIPTION
**Pull request by eldhosembabu**
- Changes to protoc version to make it working for m1 macs.

protoc v3.17.3 changelog: https://github.com/protocolbuffers/protobuf/releases/tag/v3.17.3

### CODE REVIEW

**Review by rlazo — APPROVED** [review]

**Review by rlazo — APPROVED** [review]

**Comment by eldhosembabu** [comment]
Thanks @rlazo and @schmidt-sebastian !

**Pull request merged**
