### PR TITLE
Remove format from `double` helper function

### PR DESCRIPTION
**Pull request by rlazo**
We can omit the format for the double-precision floating point type

See https://github.com/firebase/firebase-ios-sdk/pull/13990 for further context

### CODE REVIEW

**Comment by rlazo** [comment]
cc @andrewheard

**Review by andrewheard — APPROVED** [review]

**Review by daymxn — COMMENTED** [review]
Is double the default? Is this behavior we should rely on?

**Comment by rlazo** [comment]
> Is double the default? Is this behavior we should rely on?
> 
> e: I just saw the [ios issue](https://github.com/firebase/firebase-ios-sdk/pull/13990) which helped provide context.
> 
> Although, isn't this an issue with the backend? Shouldn't it enforce it?

`double` is the largest floating-point number type in Kotlin (not counting Big* numbers). As in the case of `long`, we assume the type with the largest capacity is generic enough to represent the range of values the model can return if no is format specified.

As documented in the kdoc, even if everything is working as expected, `integer` and `float` are hints in the Schema.

**Review by daymxn — APPROVED** [review]
SGTM. May be worth directly linking to andrew's PR in the PR desc for context/auditing

**Pull request merged**
