### PR TITLE
Un-hide EmulatorSettings API

### PR DESCRIPTION
**Pull request by samtstern**
Follow up to #1672 #1688 #1690

Questions:

- [x] Where is the CHANGELOG for `firebase-common` and `firebase-functions`?
- [x] Should I also bump the `-ktx` library versions?

### CODE REVIEW

**Comment by samtstern** [comment]
Assigning to @ashwinraghav for review since Vlad is out.

**Comment by rlazo** [comment]
About bumping `-ktx`, please do. Thanks!

**Comment by samtstern** [comment]
@rlazo where do I do that?  I don't see a `gradle.properties` for the KTX SDKs that contains a version number.  Do they even have their own versions or do they automatically inherit?

**Comment by rlazo** [comment]
argh... my bad. Yes, they inherit the version from the parent's `version` var. No work needed!

**Comment by rlazo** [comment]
Changelogs for `firebase-common` and `firebase-functions` are generated during the release process, you'll not be able to find them here.

**Pull request merged**
