### PR TITLE
Making transport schemas more testable

### PR DESCRIPTION
**Pull request by ashwinraghav**
There are no functional changes in this PR.
1. We have simply pulled out the `SQLiteOpenHelper` extension into a `SchemaManager` that encapsulates bootstrapping the database. In a future PR we introduce migrations into this layer.

2. Queries are parameterized for testability in future PRs.

3. We introduce a `SchemaManagerTest` that tests bootstrap and migration operations on the database.

### CODE REVIEW

**Comment by vkryachko** [comment]
Discussed offline, unification between bootstrap and migrations will be done in a follow up PR

**Comment by ashwinraghav** [comment]
Test1
Steps | Observation| Pass/Fail
------|-------------|----------
Install @ old version <br> <br> Log to cct bknd | v1_events <br> v1_contexts| Pass
Install @ new version <br> <br> Log to cctsdsd bknd | Logcat: `Transport backend 'cctsdsd' is not registered` <br> DB state is identical and losless| Pass
Install @ new version <br> <br> Log to cct bknd |v2_events| Pass
Install @ new version instantiating the right backends <br> No logs |New column addedv3_context|Pass|
Install @ new version<br> Log to lflg bknd |New context added<br>v4_context<br>New events bound to context<br>v4_events|Pass
Kill app<br>Exit airplane mode<br> Reopen app| I was unable to force a flush. The events seem to remain | Fail
Downgrade app to older sdk|Cannot emulate dropping db <br> No crashes seen while logging|Pass

**Comment by ashwinraghav** [comment]
Round 2

Test1

Steps | Observation| Pass/Fail
------|-------------|----------
Install @ old version <br> Log to cct bknd | Two contexts found. High Priority event already written. <br>Only low priority event found <br> Found Scheduled Job for low priority event <br>Screen Shot 2019-08-13 at 11 55 53 AM| Pass
Install @ new version <br> <br> Log to lflg bknd | Four contexts found. Only low priority events of cct and lflg remain<br> Found Scheduled Job for low priority lflg event. The previous Scheduled job for low priority cct event is destroyed when app is installed/upgraded<br>Screen Shot 2019-08-12 at 5 55 02 PM | Pass
Install @ new version <br> Log to cct bknd | Found only low priority events.<br> High priority cct was flushed.<br> Found jobs scheduled for low priority events of cct and lflg<br>Screen Shot 2019-08-13 at 2 00 02 PM|Pass

**Pull request merged**
