### PR TITLE
Add a null check on AnalyticsConnector provider

### PR DESCRIPTION
**Pull request by AUT0CRAT**
Creating the ConfigFetchHandler for a non-default firebase application marks the provider as null which caused a NullPointerException

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object com.google.firebase.inject.Provider.get()' on a null object reference
at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.getUserProperties(ConfigFetchHandler.java:501)
at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackend(ConfigFetchHandler.java:311)
at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.fetchFromBackendAndCacheResponse(ConfigFetchHandler.java:278)
at com.google.firebase.remoteconfig.internal.ConfigFetchHandler.lambda$fetchIfCacheExpiredAndNotThrottled$1$ConfigFetchHandler(ConfigFetchHandler.java:215)
at com.google.firebase.remoteconfig.internal.ConfigFetchHandler$$ExternalSyntheticLambda1.then(Unknown Source:8)
at com.google.android.gms.tasks.zzf.run(com.google.android.gms:play-services-tasks@@17.2.0:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)

### CODE REVIEW

**Comment by carlonzo** [comment]
https://github.com/firebase/firebase-android-sdk/pull/2714

**Comment by vkryachko** [comment]
hi @AUT0CRAT , what version of remote config were you using? Since about late last year, `Provider`s are never `null`, so this NPE should not be happening as you described.

**Comment by AUT0CRAT** [comment]
Hi @vkryachko I tested it on `28.2.1` couple of days ago and this crash still occurs. `27.1.0` works fine

**Comment by vkryachko** [comment]
@AUT0CRAT thanks for the reply. I am unable to repro locally. Getting do you mind describing repro steps or creating and sharing a small app that reproduces the problem? thanks

**Comment by AUT0CRAT** [comment]
Hi @vkryachko You can use this [sample application](https://github.com/AUT0CRAT/FirebaseRemoteConfigSecodary/tree/main) to reproduce the NPE

**Comment by vkryachko** [comment]
Hm, sorry still cannot repro with your app, here's the result of me clicking through all buttons

Screen Shot 2021-07-17 at 10 14 38 AM

Am I missing something?

**Comment by AUT0CRAT** [comment]
The reason it is not able to find the secondary remote config is because it is unable to initialize the remote config instance. If you check the logcat you will notice the NPE.

**Comment by vkryachko** [comment]
OK cool, I can finally see the issue.

I would suggest a different fix though, namely this line:
https://github.com/firebase/firebase-android-sdk/blob/52e1cf89efd795d798ae5485b8503e04e4a936b8/firebase-config/src/main/java/com/google/firebase/remoteconfig/RemoteConfigComponent.java#L241

Instead of using `null` it should use `() -> null`, which is a cleaner fix since providers are never expected to be null even if the dependency is absent.

**Comment by AUT0CRAT** [comment]
Hi @vkryachko I have made the suggested changes

**Comment by vkryachko** [comment]
@AUT0CRAT thanks a lot, waiting for tests to pass before approving

**Comment by AUT0CRAT** [comment]
@vkryachko not sure why `check-changed` failed. The link in the details does not work. Is there something I missed?

**Comment by vkryachko** [comment]
Sorry, our CI results page is undergoing a migration and is currently unavailable, if the check fails again I will provide the log details directly

**Comment by AUT0CRAT** [comment]
@vkryachko Seems it failed again, Can you please share the log details

**Comment by vkryachko** [comment]
Sure, here's the test failure:


```
com.google.firebase.remoteconfig.RemoteConfigComponentTest > getFetchHandler_nonMainFirebaseApp_doesNotUseAnalytics FAILED
    com.google.common.truth.AssertionErrorWithFacts at RemoteConfigComponentTest.java:130

com.google.firebase.perf.session.PerfSessionTest > shouldCollectGaugesAndEvents_perfMonDisabledAtBuildtime_verbosityDependsOnRuntime FAILED
    com.google.common.truth.AssertionErrorWithFacts at PerfSessionTest.java:107
```

Not sure if perf's test is flaky or needs to be updated as well(since perf uses remote config)

**Comment by AUT0CRAT** [comment]
@vkryachko updated the remote config test. The perf one seems flaky. Can you please trigger the tests

**Comment by AUT0CRAT** [comment]
@vkryachko looks like the tests aren't running, is there something that needs to be done?

**Comment by vkryachko** [comment]
Unfortunately our CI is currently down, working to resolve the issue asap, I will re-trigger your presubmits once resolved

**Comment by yifanyang** [comment]
@AUT0CRAT Our CI is partially back. I have already issued a rerun, and the tests are being scheduled/executed now.

There is still some problem with our TLS certificate, and we are using our self-signed one for the moment, which means if you try to access the log through the `Details` button, the browser will show connection as not secure. We are still working on that.

**Review by vkryachko — APPROVED** [review]

**Comment by AUT0CRAT** [comment]
Hey @vkryachko, what is the release cadence for the config library? Any ETA on when I can expect this change in production?

**Comment by vkryachko** [comment]
It will be released end of next week, please see https://firebase.google.com/support/release-notes/android for updates

**Pull request merged**
