### PR TITLE
Update target to SDK 33

### PR DESCRIPTION
**Pull request by utzcoz**
We need to update AXT core and AndroidX ext JUnit version to ensure using proper AXT dependency that export necessary Activities for higher target SDKs.

This CL also disables lint for some sub-projets and anyone can remove it and fix warnings.

### CODE REVIEW

**Comment by utzcoz** [comment]
Hi @rlazo , could you help to check three failed test suites? I can't run two test suites related to session, and I can run perf test suite without erorrs.

**Comment by rlazo** [comment]
Hi @utzcoz , thanks for your contribution! we'll need some time to test that bumping the `targetSdk` to 33 doesn't require any additional code changes across all Firebase SDKs. As to not fully block you in the meantime, we could merge all the other changes in this PR now, and do the `targetSdk` bump on its own. What do you think?

**Comment by rlazo** [comment]
Great. Add me as a reviewer once you update the PR, and update the branch, so I can approve it.

**Comment by rlazo** [comment]
sounds good to me!

**Review by rlazo — APPROVED** [review]

**Comment by rlazo** [comment]
Thank you for your contribution!

**Pull request merged**
