### PR TITLE
Add custom keys/values when recording non-fatals

### PR DESCRIPTION
**Pull request by nullptr2this**
Provides ability to pass non-fatal instance specific key/value pairs when recording non-fatals.
resolves https://github.com/firebase/firebase-android-sdk/issues/3551

### CODE REVIEW

**Review by TizioIncognito — APPROVED** [review]
The changes are ok to be merged.

**Comment by david-livefront** [comment]
Is there something holding this up or can it be merged?

**Comment by tejasd** [comment]
Thanks for the PR! We've submitted a change in #6528 that solves this issue - and so I'm closing this.

**Comment by nullptr2this** [comment]
Hahaha.  Sure thing.

**Pull request closed without merging**
