### PR TITLE
Clean up error handling in NewReleaseFetcher

### PR DESCRIPTION
**Pull request by lfkellogg**
- Cleans up top level Task-based error handling, using `TaskUtils.runAsyncInTask`
- Isolates Long parsing error handling into one place
- Improves messaging around getting IAS artifact IDs, APK hashes, package info

### CODE REVIEW

**Comment by lfkellogg** [comment]
Please hold off on reviewing this I need to make some tweaks.

**Review by rachaprince — APPROVED** [review]
This is a very nice refactor. I especially love the improvements to the TaskUtils and ReleaseIdentificationUtils classes.

Great work

**Review by mannyjimenez0810 — APPROVED** [review]

**Pull request merged**
