### PR TITLE
Adjust Functions getters to be Kotlin source compatible

### PR DESCRIPTION
**Pull request by emilypgoogle**

### CODE REVIEW

**Review by rlazo — APPROVED** [review]
Just need to fix the instrumentation tests

**Comment by rlazo** [comment]
Also, please reference https://github.com/firebase/firebase-android-sdk/issues/6522

**Comment by daymxn** [comment]
To avoid a breaking change, we'd have to use `@JvmField` with a custom getter, and make sure that the data field is public. We'd also have to duplicate our javadcos (or just add a kdoc link that points to `getData`).

```kt
/** The result of calling a HttpsCallableReference function. */
public class HttpsCallableResult
internal constructor(
  /** Backing field for [getData]. */
  @JvmSynthetic @JvmField public val data: Any?
) {
  /**
   * Returns the data that was returned from the Callable HTTPS trigger.
   *
   * The data is in the form of native Java objects. For example, if your trigger returned an array,
   * this object would be a List<Object>. If your trigger returned a JavaScript object with keys and
   * values, this object would be a Map<String, Object>.
   */
  public fun getData(): Any? {
    return data
  }
}

```

This will allow kotlin consumers to call `.data` _and_ `.getData()`.

But Java consumers can _also_ call `.data` _and_ `.getData()`.

We can block java consumers from using it by using `@JvmSynthetic`, but this can negatively impact stack traces. We can also do `@JvmName("--data")`, and that'll also hide it without hurting stack traces- but it's a bandaid if anything.

Seeing as how removing `.data` in the future would be a breaking change regardless, I'd argue that it's fine to expose it to java consumers. So just using `@JvmField` should be fine. wdyt @rlazo ?

**Comment by rlazo** [comment]
> To avoid a breaking change, we'd have to use `@JvmField` with a custom getter, and make sure that the data field is public. We'd also have to duplicate our javadcos (or just add a kdoc link that points to `getData`).
> 
> ```kotlin
> /** The result of calling a HttpsCallableReference function. */
> public class HttpsCallableResult
> internal constructor(
>   /** Backing field for [getData]. */
>   @JvmSynthetic @JvmField public val data: Any?
> ) {
>   /**
>    * Returns the data that was returned from the Callable HTTPS trigger.
>    *
>    * The data is in the form of native Java objects. For example, if your trigger returned an array,
>    * this object would be a List<Object>. If your trigger returned a JavaScript object with keys and
>    * values, this object would be a Map<String, Object>.
>    */
>   public fun getData(): Any? {
>     return data
>   }
> }
> ```
> 
> This will allow kotlin consumers to call `.data` _and_ `.getData()`.
> 
> But Java consumers can _also_ call `.data` _and_ `.getData()`.
> 
> We can block java consumers from using it by using `@JvmSynthetic`, but this can negatively impact stack traces. We can also do `@JvmName("--data")`, and that'll also hide it without hurting stack traces- but it's a bandaid if anything.
> 
> Seeing as how removing `.data` in the future would be a breaking change regardless, I'd argue that it's fine to expose it to java consumers. So just using `@JvmField` should be fine. wdyt @rlazo ?

SGTM

**Pull request merged**
