### PR TITLE
Implement firebase-database coroutine extension

### PR DESCRIPTION
**Pull request by msasikanth**
Doesn't support generics like List<> and Map<> unless suspended function is inlined and type is reified

### CODE REVIEW

**Comment by rosariopfernandes** [comment]
@msasikanth any specific reason why we can't inline the function and use reified type? It would be nice if it could support generics.

**Comment by msasikanth** [comment]
> @msasikanth any specific reason why we can't inline the function and use reified type? It would be nice if it could support generics.

Inline calls like this may increase byte code at call site. But I maybe wrong, if it's fine I can make this function inline

**Comment by rlazo** [comment]
Thanks a lot for your contribution @msasikanth ! I'll get back to you after the changes have been reviewed internally.

**Comment by msasikanth** [comment]
> Thanks a lot for your contribution @msasikanth ! I'll get back to you after the changes have been reviewed internally.

Awesome. One test failed because of ':firebase-database:ktx:generateLicenses', what this supposed to happen?

**Comment by rlazo** [comment]
> > Thanks a lot for your contribution @msasikanth ! I'll get back to you after the changes have been reviewed internally.
> 
> Awesome. One test failed because of ':firebase-database:ktx:generateLicenses', was this supposed to happen?

It's most likely a temporal issue. I've re-run the test to confirm.

**Comment by rlazo** [comment]
> > > Thanks a lot for your contribution @msasikanth ! I'll get back to you after the changes have been reviewed internally.
> > 
> > 
> > Awesome. One test failed because of ':firebase-database:ktx:generateLicenses', was this supposed to happen?
> 
> It's most likely a temporal issue. I've re-run the test to confirm.

This is actually caused by a bug in our license fetcher. I'll fix it in a separate PR.

**Comment by rlazo** [comment]
> > > > Thanks a lot for your contribution @msasikanth ! I'll get back to you after the changes have been reviewed internally.
> > > 
> > > 
> > > Awesome. One test failed because of ':firebase-database:ktx:generateLicenses', was this supposed to happen?
> > 
> > 
> > It's most likely a temporal issue. I've re-run the test to confirm.
> 
> This is actually caused by a bug in our license fetcher. I'll fix it in a separate PR.

https://github.com/firebase/firebase-android-sdk/pull/868 addresses the issue.

**Comment by msasikanth** [comment]
> > > > > Thanks a lot for your contribution @msasikanth ! I'll get back to you after the changes have been reviewed internally.
> > > > 
> > > > 
> > > > Awesome. One test failed because of ':firebase-database:ktx:generateLicenses', was this supposed to happen?
> > > 
> > > 
> > > It's most likely a temporal issue. I've re-run the test to confirm.
> > 
> > 
> > This is actually caused by a bug in our license fetcher. I'll fix it in a separate PR.
> 
> #868 addresses the issue.

I accidentally forgot and pushed the latest changes from firebase/firebase-android-sdk. Should I open another PR with just the coroutines commit?

**Comment by rlazo** [comment]
Thanks for your contribution @msasikanth! We've reviewed it internally and while we think it provides ease of use, it differs from the general approach we are using in firebase-database. We are evaluating what's the best approach to use throughout all SDKs, and we'd like to keep the API consistent in the meanwhile. Once again, thanks for your contribution to Firebase!

**Pull request closed without merging**
